import OpenAI from 'openai';
import dotenv from 'dotenv';

dotenv.config();

const apiKey = process.env.OPENAI_API_KEY;
// Prioritize OPENAI_BASE_URL if set (common convention), fallback to AI_BASE_URL, then default to OpenAI
const baseURL = process.env.OPENAI_BASE_URL || process.env.AI_BASE_URL || 'https://api.openai.com/v1';
const model = process.env.AI_MODEL || 'gpt-3.5-turbo';

if (!apiKey) {
  console.warn('Warning: OPENAI_API_KEY is not set in .env file. AI features will not work.');
} else {
    if (baseURL.includes('openrouter')) {
        console.log(`🔌 Connected to OpenRouter (Model: ${model})`);
    } else {
        console.log(`🔌 Connected to AI Provider (Model: ${model})`);
    }
}

const openai = new OpenAI({
  apiKey: apiKey || 'dummy-key',
  baseURL: baseURL,
});

export const generateCompletion = async (prompt: string, systemPrompt: string = 'You are a helpful assistant.'): Promise<string> => {
  if (!apiKey) {
    console.warn('OPENAI_API_KEY is missing. Returning MOCK response.');
    
    // Mock responses for different agents/tasks
    if (prompt.includes('Return a JSON array of strings indicating the tools to run')) {
        // Auto-Pilot Plan Mock
        if (prompt.includes('REQUIREMENTS.md') || prompt.includes('TODO.md')) {
            return '["project-manager"]';
        }
        if (prompt.includes('.ts') || prompt.includes('.js')) {
            return '["test-gen", "doc-gen", "vuln-scan"]';
        }
        return '["doc-gen"]';
    }
    
    // Project Manager Mocks
    if (prompt.includes('Analyze this requirement (which might be a README or a raw string)')) {
        return 'Product Manager: Epic: Dark Mode. Acceptance Criteria: Toggle switch, persistence.';
    }
    if (prompt.includes('outline the technical architecture')) {
        return 'Architect: Use CSS Variables for theming. LocalStorage for persistence.';
    }
    if (prompt.includes('Break this project down into a list of actionable tasks')) {
        return '["Create Theme Context", "Add Toggle Component", "Implement LocalStorage logic"]';
    }
    
    if (prompt.includes('Generate unit tests')) {
        return `
import { add, subtract } from './sample'; // Assumption

describe('Generated Tests', () => {
    test('add should return sum', () => {
        expect(add(1, 2)).toBe(3);
    });
});
        `;
    }

    if (prompt.includes('Analyze the provided code for security vulnerabilities')) {
        return 'NO_ISSUES';
    }

    if (prompt.includes('improve the documentation')) {
        return '# Generated Documentation\n\nThis is a mock documentation generated by AutoBot.';
    }

    if (prompt.includes('provide the FULL refactored file content') || prompt.includes('Apply the necessary fixes')) {
        return `
\`\`\`typescript
// Fixed Code
export const fixedFunction = () => {
    console.log("This code was fixed by AutoBot!");
};
\`\`\`
        `;
    }

    if (prompt.includes('Review the following code implementation')) {
        return 'APPROVED';
    }

    // Mock for Team Huddle in Project Manager
    if (prompt.includes('Identify key implementation challenges')) {
        return 'Software Engineer: We should use React Context for state management. Potential challenge: re-renders.';
    }
    if (prompt.includes('Outline the testing strategy')) {
        return 'QA Engineer: Strategy: Unit tests for utils, E2E for critical flows using Cypress.';
    }
    if (prompt.includes('Identify potential security risks')) {
        return 'Security Engineer: Risk: XSS in user input. Mitigation: Sanitize all inputs.';
    }

    if (prompt.includes('Implement the requested feature/fix')) {
        return `
\`\`\`typescript
export const binarySearch = (arr: number[], target: number): number => {
    let left = 0;
    let right = arr.length - 1;
    while (left <= right) {
        const mid = Math.floor((left + right) / 2);
        if (arr[mid] === target) return mid;
        if (arr[mid] < target) left = mid + 1;
        else right = mid - 1;
    }
    return -1;
};
\`\`\`
        `;
    }

    return 'Mock AI Response';
  }

  try {
    const completion = await openai.chat.completions.create({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: prompt },
      ],
      model: model,
    });

    return completion.choices[0].message.content || '';
  } catch (error) {
    console.error('Error calling OpenAI:', error);
    throw error;
  }
};
