import { AutoBotPlugin } from '../../types';
import { consultAgent, AgentRole } from '../../services/agentService';
import { VcsFactory } from '../../services/vcs/VcsFactory';
import { runDevCycle } from '../dev-cycle';
import path from 'path';
import fs from 'fs';
import { inferLanguageFromText, getExtensionForLanguage, getFeatureSlugFromTitle } from '../../services/languageUtils';

export const runAgileWorkflow = async (issueNumber: number, title: string, description: string): Promise<void> => {
    console.log(`\n🚀 Starting Agile Workflow for Issue #${issueNumber}: ${title}`);
    
    // Tag the issue
    const vcs = VcsFactory.getProvider();
    await vcs.addLabels(issueNumber, ['autobot']);

    try {
        // Step 1: Product Manager - Clarify and Plan
        console.log('\n--- Step 1: Product Manager Planning ---');
        const pmPlan = await consultAgent(
            AgentRole.PRODUCT_MANAGER,
            `Analyze the following issue and create a clear product plan.
            Issue: ${title}
            Description: ${description}
            
            Output:
            1. User Story (As a... I want... So that...)
            2. Acceptance Criteria (List of verifyable checks)
            3. Business Value
            `,
            ''
        );
        
        await vcs.addComment(issueNumber, `### 📋 Product Plan\n\n${pmPlan}\n\n*Generated by AutoBot PM Agent*`);
        console.log('PM Plan posted to Issue.');

        // Step 2: Scrum Master - Task Breakdown
        console.log('\n--- Step 2: Scrum Master Task Breakdown ---');
        const smTasks = await consultAgent(
            AgentRole.SCRUM_MASTER,
            `Based on the PM's plan, break this down into technical tasks for the developer.
            
            PM Plan:
            ${pmPlan}
            
            Output:
            - List of specific technical tasks to implement.
            - Identify the primary file(s) that need to be created or modified.
            `,
            ''
        );

        await vcs.addComment(issueNumber, `### 🗓️ Sprint Tasks\n\n${smTasks}\n\n*Generated by AutoBot Scrum Master*`);
        console.log('Scrum Tasks posted to Issue.');

        // Step 3: Developer & QA Execution (Trigger Dev Cycle)
        console.log('\n--- Step 3: Execution (Dev & QA) ---');
        
        const safeTitle = getFeatureSlugFromTitle(title);
        const languageHint = inferLanguageFromText(`${title}\n${description}\n${pmPlan}\n${smTasks}`);
        const fileExt = getExtensionForLanguage(languageHint);
        const targetFile = path.join(process.cwd(), 'src', 'features', `${safeTitle}${fileExt}`);
        
        // Ensure dir exists
        const dir = path.dirname(targetFile);
        if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

        // Augment the task for the developer with the context from PM and SM
        const robustTask = `
        Issue: ${title}
        ${description}
        
        PM Requirements:
        ${pmPlan}
        
        Technical Tasks:
        ${smTasks}
        `;

        const prUrl = await runDevCycle(robustTask, targetFile, issueNumber);

        // Step 4: Completion
        await vcs.addComment(issueNumber, `### ✅ Workflow Complete\n\nCode has been implemented and tested.\n\n### 🔗 PR\n${prUrl || 'PR link unavailable.'}`);

    } catch (error) {
        console.error('Error in Agile Workflow:', error);
        await vcs.addComment(issueNumber, `### ❌ Workflow Failed\n\nAn error occurred: ${error}`);
    }
};

const plugin: AutoBotPlugin = {
    name: 'Agile Workflow',
    description: 'Full pipeline: PM -> Scrum Master -> Dev -> QA',
    command: 'agile',
    args: [
        { name: 'issue', description: 'Issue number', required: true },
        { name: 'title', description: 'Issue title', required: true }
    ],
    action: async (...args: any[]) => {
        // CLI usage might differ from Webhook usage, but here's a basic CLI entry
        const issue = args[0];
        const title = args[1];
        await runAgileWorkflow(Number(issue), title, 'No description provided via CLI');
    }
};

export default plugin;
