import { OrchestraPlugin } from '../../types';
import fs from 'fs';
import path from 'path';
import { consultAgent, AgentRole } from '../../services/agentService';
import { extractCodeBlock } from '../../utils/codeExtractor';
import { createBranch, commitChanges, pushChanges, buildBranchName } from '../../services/gitService';
import { VcsFactory } from '../../services/vcs/VcsFactory';
import { inferLanguageFromExtension } from '../../services/languageUtils';

export const fixCode = async (filePath: string, instruction?: string): Promise<void> => {
  console.log(`Analyzing ${filePath} for fixes...`);

  try {
    if (!fs.existsSync(filePath)) {
      console.error(`File not found: ${filePath}`);
      return;
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    const codeLanguage = inferLanguageFromExtension(filePath);

    const task = instruction || 'Fix any bugs, logical errors, or code smells in the following code.';

    // Step 1: Software Engineer analyzes and fixes
    const fixSuggestion = await consultAgent(
        AgentRole.SOFTWARE_ENGINEER,
        `Task: ${task}
        
Instructions:
1. Analyze the code provided below.
2. Apply the necessary fixes or refactoring based on the task.
3. Output ONLY the FULL corrected file content, with no explanations or markdown formatting.
4. Do not output partial code.
`,
        content
    );

    const fixedCode = extractCodeBlock(fixSuggestion) || fixSuggestion;

    if (fixedCode) {
        if (fixedCode === content.trim()) {
            console.log('No changes needed.');
            return;
        }

        const backupPath = `${filePath}.bak`;
        fs.writeFileSync(backupPath, content);
        console.log(`\nOriginal file backed up to: ${backupPath}`);
        
        fs.writeFileSync(filePath, fixedCode);
        console.log(`✅ Applied fix to: ${filePath}`);

        // Create Branch and PR
        const fileName = filePath.split('/').pop();
        const branchName = buildBranchName('fix-code', instruction || fileName || '');
        const commitMsg = instruction ? `fix: ${instruction}` : `refactor: update ${fileName}`;

        try {
            console.log(`\nInitiating Git workflow for fix...`);
            await createBranch(branchName);
            await commitChanges(commitMsg, [filePath]);
            await pushChanges(branchName);

            const vcs = VcsFactory.getProvider();
            const prUrl = await vcs.createPullRequest(
                `Fix: ${fileName}`,
                branchName,
                'main',
                `## Description\n${instruction || 'Applied automated fixes.'}\n\n*Generated by Orchestra Code Fixer*`
            );

            if (prUrl) {
                console.log(`Pull Request created successfully: ${prUrl}`);
            }
        } catch (gitError) {
            console.error('Git workflow failed (might be running locally without upstream):', gitError);
        }
    } else {
        console.warn('Could not extract code from AI response.');
        console.log('AI Response:', fixSuggestion);
    }

  } catch (error) {
    console.error('Error applying fix:', error);
  }
};

const plugin: OrchestraPlugin = {
  name: 'Code Fixer',
  description: 'Apply AI-driven fixes or refactoring to a file',
  command: 'fix',
  args: [
    { name: 'path', description: 'Path to the file to fix', required: true },
    { name: 'instruction', description: 'Specific instruction (e.g., "Fix the null pointer exception")', required: false }
  ],
  action: async (path: string, instruction?: string) => {
    // Commander passes args differently if variadic or optional.
    // If instruction is the command object, it means it wasn't provided.
    if (typeof instruction === 'object') instruction = undefined;
    await fixCode(path, instruction);
  }
};

export default plugin;
