spec:
  inputs:
    image:
      default: node:20
      description: "Docker image to use"
    stage:
      default: test
      description: "Pipeline stage to run in"

---

.orchestra_base:
  image: $[[ inputs.image ]]
  before_script:
    - npm install -g orchestra-svemind
  variables:
    VCS_PROVIDER: gitlab

orchestra-auto:
  extends: .orchestra_base
  stage: $[[ inputs.stage ]]
  script:
    - orchestra auto
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

orchestra-vuln-scan:
  extends: .orchestra_base
  stage: $[[ inputs.stage ]]
  script:
    - orchestra vuln-scan .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

orchestra-release-notes:
  extends: .orchestra_base
  stage: deploy
  script:
    - orchestra release-notes $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
