import { AutoBotPlugin } from '../../types';
import { consultAgent, AgentRole } from '../../services/agentService';
import { createIssue } from '../../services/githubService';
import fs from 'fs';

export const manageProject = async (input: string, instruction?: string): Promise<void> => {
  let requirement = input;
  
  // Check if input is a file path (e.g., README.md)
  if (fs.existsSync(input)) {
      console.log(`Reading requirements from file: ${input}`);
      requirement = fs.readFileSync(input, 'utf-8');
  }

  // If specific instruction is provided, prepend it to the requirement context
  if (instruction) {
      console.log(`Using custom instruction: "${instruction}"`);
      requirement = `INSTRUCTION: ${instruction}\n\nCONTEXT:\n${requirement}`;
  }

  console.log(`Initiating Project Management...`);

  try {
    // Step 1: Product Manager defines the requirements/epics
    const pmAnalysis = await consultAgent(
        AgentRole.PRODUCT_MANAGER,
        'Analyze this requirement (which might be a README or a raw string). Break it down into clear acceptance criteria and business value.',
        requirement
    );
    console.log(`\n[Product Manager]:\n${pmAnalysis}`);

    // Step 2: Architect designs the solution
    const architectDesign = await consultAgent(
        AgentRole.ARCHITECT,
        'Based on the requirements, outline the technical architecture and necessary components.',
        pmAnalysis
    );
    console.log(`\n[Architect]:\n${architectDesign}`);

    // Step 3: Team Huddle (Parallel Consultation)
    console.log(`\nGathering Team Input (Huddle)...`);
    const [devInput, qaInput, secInput] = await Promise.all([
        consultAgent(AgentRole.SOFTWARE_ENGINEER, 'Review the requirements and architecture. Identify key implementation challenges and libraries needed.', `${pmAnalysis}\n${architectDesign}`),
        consultAgent(AgentRole.QA_ENGINEER, 'Review the requirements. Outline the testing strategy and key test cases.', pmAnalysis),
        consultAgent(AgentRole.SECURITY_ENGINEER, 'Review the architecture. Identify potential security risks and mitigations.', architectDesign)
    ]);

    // Step 4: Scrum Master breaks it down into tasks
    const tasksRaw = await consultAgent(
        AgentRole.SCRUM_MASTER,
        'Break this project down into a list of actionable tasks for the dev team. Output as a JSON list of strings.',
        `Requirements:\n${pmAnalysis}\n\nArchitecture:\n${architectDesign}\n\nDev Notes:\n${devInput}\n\nQA Strategy:\n${qaInput}\n\nSecurity Risks:\n${secInput}`
    );
    
    // Attempt to parse JSON tasks, fallback to splitting lines if AI fails strict JSON
    let tasks: string[] = [];
    try {
        tasks = JSON.parse(tasksRaw.match(/\[.*\]/s)?.[0] || '[]');
    } catch (e) {
        tasks = tasksRaw.split('\n').filter(line => line.trim().startsWith('-')).map(line => line.replace('-', '').trim());
    }

    console.log(`\n[Scrum Master] Generated ${tasks.length} tasks.`);

    // Step 5: Create Issues for each task in PARALLEL
    console.log(`\nStarting parallel issue creation for ${tasks.length} tasks...`);
    
    const issuePromises = tasks.map(async (task) => {
        console.log(`Processing Task: ${task}`);
        
        // UX Designer input if needed
        let additionalContext = '';
        if (task.toLowerCase().includes('ui') || task.toLowerCase().includes('frontend') || task.toLowerCase().includes('design')) {
             const uxInput = await consultAgent(AgentRole.UX_DESIGNER, 'Provide UX guidelines for this task.', task);
             additionalContext += `\n\n**UX Guidelines:**\n${uxInput}`;
        }

        const issueBody = `
## Task Description
${task}

## Technical Context (Architect)
${architectDesign.substring(0, 300)}...

## Implementation Notes (Dev)
${devInput.substring(0, 300)}...

## QA Strategy
${qaInput.substring(0, 300)}...

## Security Considerations
${secInput.substring(0, 300)}...

${additionalContext}

*Generated by AutoBot Project Manager*
        `;

        await createIssue(task, issueBody, ['autobot-task', 'todo']);
        console.log(`  -> Issue created: ${task.substring(0, 30)}...`);
    });

    await Promise.all(issuePromises);

    console.log('\nProject breakdown completed.');

  } catch (error) {
    console.error('Error in project manager:', error);
  }
};

const plugin: AutoBotPlugin = {
  name: 'Project Manager',
  description: 'Simulate an agile team to breakdown requirements (from string or file) and create issues',
  command: 'project-manager',
  args: [
    { name: 'input', description: 'The feature requirement or path to a file (e.g., README.md)', required: true },
    { name: 'instruction', description: 'Optional instruction or prompt', required: false }
  ],
  action: async (input: string, instruction?: string) => {
        await manageProject(input, instruction);
    }
};

export default plugin;
